site_name: Greyhawk Spielerwissen
site_description: Oeffentliche Kampagnennotizen fuer Spieler
site_url: https://nillorian.github.io/logseq-greyhawk-public/
repo_url: https://github.com/nillorian/logseq-greyhawk-public

theme:
  name: material
  language: de
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

docs_dir: pages
site_dir: site

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Start: index.md
  - Inhaltsseite: contents.md
